# Generated by Django 4.2.29 on 2026-03-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
    ]
