# Generated by Django 4.2.29 on 2026-03-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_customuser_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='num_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
