# Generated by Django 6.0.5 on 2026-05-14 12:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Student", "Student"),
                            ("Admin", "Admin"),
                            ("Sub Admin", "Sub Admin"),
                        ],
                        db_index=True,
                        default="Student",
                        help_text="Determines UI experience.",
                        max_length=15,
                    ),
                ),
                (
                    "raw_password",
                    models.CharField(
                        blank=True,
                        help_text="Store original password for display in admin dashboard (User requirement).",
                        max_length=255,
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        help_text="WhatsApp number for direct contact.",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="WhatsApp number must be 9-15 digits, optionally starting with +.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Primary contact number.",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be 9-15 digits, optionally starting with +.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Student profile picture.",
                        null=True,
                        upload_to="profile_photos/%Y/%m/",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, help_text="Student date of birth.", null=True
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, help_text="Full postal address."),
                ),
                (
                    "institution",
                    models.CharField(
                        blank=True,
                        help_text="School / college / university name.",
                        max_length=200,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the exam category.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief overview of what this category covers.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this category is visible to students.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="idx_cat_name"),
                    models.Index(fields=["-created_at"], name="idx_cat_created"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("marks", models.DecimalField(decimal_places=2, max_digits=7)),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("total_marks", models.PositiveIntegerField()),
                ("exam_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="exams.category",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate",
                "verbose_name_plural": "Certificates",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamPaper",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_marks",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Sum of marks for all included questions (cached on generation).",
                    ),
                ),
                (
                    "total_duration_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Sum of per-question time limits in minutes (cached on generation).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category this exam belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_papers",
                        to="exams.category",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student this paper was generated for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_papers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Paper",
                "verbose_name_plural": "Exam Papers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="Pending",
                        max_length=10,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for rejection (filled by admin if rejected).",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the admin reviewed this request.",
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category the student wants to take an exam in.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="exams.category",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who reviewed this request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student requesting exam access.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Request",
                "verbose_name_plural": "Exam Requests",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("Approval", "Approval"),
                            ("Rejection", "Rejection"),
                            ("Info", "Information"),
                            ("Result", "Result Available"),
                        ],
                        db_index=True,
                        default="Info",
                        max_length=15,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short notification title.", max_length=200
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="Full notification message body."),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the recipient has read this notification.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="User who receives this notification.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique question identifier.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        db_index=True,
                        default="Medium",
                        help_text="Difficulty tier for balanced paper generation.",
                        max_length=10,
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("MCQ", "Multiple Choice"),
                            ("Short Answer", "Short Answer"),
                            ("Essay", "Essay"),
                            ("True/False", "True / False"),
                        ],
                        db_index=True,
                        default="MCQ",
                        help_text="Determines answer input format on the student interface.",
                        max_length=20,
                    ),
                ),
                (
                    "question_text",
                    models.TextField(
                        help_text="Full question statement displayed to the student."
                    ),
                ),
                (
                    "option_a",
                    models.CharField(
                        blank=True,
                        help_text="Option A (MCQ / True-False).",
                        max_length=500,
                    ),
                ),
                (
                    "option_b",
                    models.CharField(
                        blank=True,
                        help_text="Option B (MCQ / True-False).",
                        max_length=500,
                    ),
                ),
                (
                    "option_c",
                    models.CharField(
                        blank=True, help_text="Option C (MCQ).", max_length=500
                    ),
                ),
                (
                    "option_d",
                    models.CharField(
                        blank=True, help_text="Option D (MCQ).", max_length=500
                    ),
                ),
                (
                    "correct_answer",
                    models.CharField(
                        help_text="The correct answer. For MCQ, store the option letter (A/B/C/D).",
                        max_length=500,
                    ),
                ),
                (
                    "marks",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Marks awarded for a correct answer (1-100).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "time_limit_minutes",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Per-question time limit in minutes (1-120).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Soft-delete flag. Inactive questions are excluded from paper generation.",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Linked category for this question.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who created or imported this question.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamPaperQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Presentation order of this question within the paper.",
                    ),
                ),
                (
                    "exam_paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_questions",
                        to="exams.exampaper",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paper_inclusions",
                        to="exams.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Paper Question",
                "verbose_name_plural": "Exam Paper Questions",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="exampaper",
            name="questions",
            field=models.ManyToManyField(
                help_text="Questions included in this paper (via through model).",
                related_name="exam_papers",
                through="exams.ExamPaperQuestion",
                to="exams.question",
            ),
        ),
        migrations.CreateModel(
            name="StudentExamResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "total_marks_obtained",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Auto-calculated sum of marks from correct answers.",
                        max_digits=7,
                    ),
                ),
                (
                    "total_marks_possible",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Mirrors exam_paper.total_marks for quick access.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("In Progress", "In Progress"),
                            ("Submitted", "Submitted"),
                            ("Evaluated", "Evaluated"),
                        ],
                        db_index=True,
                        default="In Progress",
                        max_length=15,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the student started the exam.",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the student submitted their answers.",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When auto-evaluation finished.",
                        null=True,
                    ),
                ),
                (
                    "exam_paper",
                    models.OneToOneField(
                        help_text="The specific paper this result corresponds to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="result",
                        to="exams.exampaper",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student who took this exam.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Exam Result",
                "verbose_name_plural": "Student Exam Results",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_answer",
                    models.TextField(
                        blank=True,
                        help_text="The student's submitted answer text or option letter.",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False,
                        help_text="Set by auto_evaluate for MCQ/True-False.",
                    ),
                ),
                (
                    "marks_awarded",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Marks awarded for this answer.",
                        max_digits=5,
                    ),
                ),
                (
                    "answered_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this answer was submitted.",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_answers",
                        to="exams.question",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="exams.studentexamresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Answer",
                "verbose_name_plural": "Student Answers",
                "ordering": ["result", "question"],
            },
        ),
        migrations.CreateModel(
            name="SubAdminOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subadmin_otps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["role"], name="idx_user_role"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["-date_joined"], name="idx_user_joined"),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["email"], name="idx_user_email"),
        ),
        migrations.AlterUniqueTogether(
            name="certificate",
            unique_together={("student", "category")},
        ),
        migrations.AddIndex(
            model_name="examrequest",
            index=models.Index(
                fields=["status", "student", "category"], name="idx_req_stat_stud_cat"
            ),
        ),
        migrations.AddIndex(
            model_name="examrequest",
            index=models.Index(
                fields=["status", "student"], name="idx_req_status_student"
            ),
        ),
        migrations.AddIndex(
            model_name="examrequest",
            index=models.Index(
                fields=["status", "-requested_at"], name="idx_req_status_date"
            ),
        ),
        migrations.AddIndex(
            model_name="examrequest",
            index=models.Index(
                fields=["student", "-requested_at"], name="idx_req_student_date"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "-created_at"], name="idx_notif_recip_date"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read", "-created_at"], name="idx_notif_unread"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["category", "difficulty"], name="idx_q_cat_diff"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["category", "difficulty", "is_active"],
                name="idx_q_cat_diff_active",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["question_type", "is_active"], name="idx_q_type_active"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["-created_at"], name="idx_q_created"),
        ),
        migrations.AddIndex(
            model_name="exampaperquestion",
            index=models.Index(
                fields=["exam_paper", "order"], name="idx_epq_paper_order"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="exampaperquestion",
            unique_together={("exam_paper", "question")},
        ),
        migrations.AddIndex(
            model_name="exampaper",
            index=models.Index(
                fields=["student", "category", "-created_at"], name="idx_paper_stud_cat"
            ),
        ),
        migrations.AddIndex(
            model_name="exampaper",
            index=models.Index(
                fields=["student", "-created_at"], name="idx_paper_student"
            ),
        ),
        migrations.AddIndex(
            model_name="studentexamresult",
            index=models.Index(
                fields=["student", "-started_at"], name="idx_result_student"
            ),
        ),
        migrations.AddIndex(
            model_name="studentexamresult",
            index=models.Index(fields=["status"], name="idx_result_status"),
        ),
        migrations.AddIndex(
            model_name="studentexamresult",
            index=models.Index(fields=["-completed_at"], name="idx_result_completed"),
        ),
        migrations.AddIndex(
            model_name="studentanswer",
            index=models.Index(fields=["result", "question"], name="idx_sa_result_q"),
        ),
        migrations.AddIndex(
            model_name="studentanswer",
            index=models.Index(fields=["is_correct"], name="idx_sa_correct"),
        ),
        migrations.AlterUniqueTogether(
            name="studentanswer",
            unique_together={("result", "question")},
        ),
    ]
