# Generated by Django 4.2 on 2026-04-02 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="name",
        ),
        migrations.AddField(
            model_name="customuser",
            name="whatsapp_number",
            field=models.CharField(
                blank=True,
                help_text="WhatsApp number for direct contact.",
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="WhatsApp number must be 9-15 digits, optionally starting with +.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Primary contact number.",
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be 9-15 digits, optionally starting with +.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
    ]
