# Generated by Django 4.2 on 2026-04-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Whether this category is visible to students.",
            ),
        ),
    ]
