# Generated by Django 6.0.7 on 2026-08-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_customuser_admission_number_customuser_roll_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="institution",
            field=models.CharField(
                blank=True, help_text="College or institution name.", max_length=150
            ),
        ),
    ]
