# Generated by Django 6.0.5 on 2026-05-11 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0004_category_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_verified", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                help_text="Linked category for this question.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="exams.category",
            ),
        ),
    ]
