# Generated by Django 5.2.17 on 2026-09-09 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_customuser_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pass_mark',
            field=models.DecimalField(decimal_places=2, default=35.0, help_text='Students must score above this percentage to pass and receive a certificate.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
