# Generated by Django 6.0.5 on 2026-05-11 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0005_registrationotp_alter_question_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="raw_password",
            field=models.CharField(
                blank=True,
                help_text="Store original password for display in admin dashboard (User requirement).",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("Student", "Student"),
                    ("Admin", "Admin"),
                    ("Sub Admin", "Sub Admin"),
                ],
                db_index=True,
                default="Student",
                help_text="Determines UI experience.",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="SubAdminOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subadmin_otps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
