# Generated by Django 6.0.5 on 2026-05-11 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0007_alter_studentanswer_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_answers",
                to="exams.question",
            ),
        ),
        migrations.AlterField(
            model_name="studentexamresult",
            name="exam_paper",
            field=models.OneToOneField(
                help_text="The specific paper this result corresponds to.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="result",
                to="exams.exampaper",
            ),
        ),
    ]
