# Generated by Django 6.0.5 on 2026-05-11 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0008_alter_studentanswer_question_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otp",
            name="user",
        ),
        migrations.DeleteModel(
            name="RegistrationOTP",
        ),
        migrations.RemoveField(
            model_name="subadminotp",
            name="user",
        ),
        migrations.DeleteModel(
            name="OTP",
        ),
        migrations.DeleteModel(
            name="SubAdminOTP",
        ),
    ]
