# Generated by Django 6.0.5 on 2026-05-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0010_otp_subadminotp_certificate"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notification",
            name="idx_notif_recip_date",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="idx_notif_unread",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="recipient",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether the user has read this notification.",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("Registration", "Student Registration"),
                    ("Login", "User Login"),
                    ("Exam Complete", "Exam Completion"),
                    ("Certificate", "Certificate Generation"),
                    ("High Score", "High Score (>=85%)"),
                    ("Category Delete", "Category Deletion"),
                    ("Question Delete", "Question Deletion"),
                    ("Approval", "Approval"),
                    ("Rejection", "Rejection"),
                    ("Info", "Information"),
                ],
                db_index=True,
                default="Info",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_notif_user_date"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read", "-created_at"], name="idx_notif_unread"
            ),
        ),
    ]
