# Generated by Django 6.0.5 on 2026-05-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0011_remove_notification_idx_notif_recip_date_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notification",
            name="idx_notif_user_date",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="idx_notif_unread",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="user",
            new_name="recipient",
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether the recipient has read this notification.",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("Approval", "Approval"),
                    ("Rejection", "Rejection"),
                    ("Info", "Information"),
                    ("Result", "Result Available"),
                ],
                db_index=True,
                default="Info",
                max_length=15,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "-created_at"], name="idx_notif_recip_date"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read", "-created_at"], name="idx_notif_unread"
            ),
        ),
    ]
